name: App_TestPy_Workflow

on:
  pull_request:
    branches:
      - dev
      - prod
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: |
         sudo apt-get update && apk add postgresql-dev gcc python3-dev musl-dev zlib-dev jpeg-dev graphviz-dev libpq
      - name: Install dependencies
        run: |
          ls -l .
          cd ./test-app-backend
          pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Test with pytest
        run: pytest



